### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by kartikchandran** [briney/scab#7]
Hello,
I'm trying to install scab on my Mac OS X laptop (M1 Mac, running Monterey 12.6.3) and got the following error.
I was wondering if could help me figure this out—thank you!
Kartik

` Building wheel for mnnpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kartik/opt/miniconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-5rmdedry/mnnpy_b4d14857c7794942a2287aa0e0b50d8a/setup.py'"'"'; __file__='"'"'/private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-5rmdedry/mnnpy_b4d14857c7794942a2287aa0e0b50d8a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-wheel-bm_7wqmf
       cwd: /private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-5rmdedry/mnnpy_b4d14857c7794942a2287aa0e0b50d8a/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  file irlb.py (for module irlb) not found
  file mnn.py (for module mnn) not found
  file utils.py (for module utils) not found
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/irlb.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/utils.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/mnn.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/settings.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  file irlb.py (for module irlb) not found
  file mnn.py (for module mnn) not found
  file utils.py (for module utils) not found
  running build_ext
  building 'mnnpy._utils' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/mnnpy
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kartik/opt/miniconda3/include -arch x86_64 -I/Users/kartik/opt/miniconda3/include -arch x86_64 -Imnnpy -I/Users/kartik/opt/miniconda3/include/python3.7m -c mnnpy/_utils.c -o build/temp.macosx-10.9-x86_64-3.7/mnnpy/_utils.o -O2 -ffast-math -march=native -fopenmp
  clang: error: unsupported option '-fopenmp'
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mnnpy
`

**Comment by kartikchandran** [comment]
I also tried the directions here: https://stackoverflow.com/questions/60005176/how-to-deal-with-clang-error-unsupported-option-fopenmp-on-travis

On apple's llvm, -fopenmp is not supported. One should use brew's llvm.
The following commands will allow linking openmp:
brew install llvm libomp
export CC=/usr/local/opt/llvm/bin/clang

When I ran this and then tried installing scab, I got the following (different) error (with mnnpy again).
Any advice would be appreciated—thanks!
kc

`Building wheels for collected packages: mnnpy
  Building wheel for mnnpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kartik/opt/miniconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-byz9g9co/mnnpy_ff0c0ada709a4e1d94f7e7554653fa5c/setup.py'"'"'; __file__='"'"'/private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-byz9g9co/mnnpy_ff0c0ada709a4e1d94f7e7554653fa5c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-wheel-h6g_j6m6
       cwd: /private/var/folders/y6/hvkqctp16wx9gjzshcv34pnm0000gn/T/pip-install-byz9g9co/mnnpy_ff0c0ada709a4e1d94f7e7554653fa5c/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  file irlb.py (for module irlb) not found
  file mnn.py (for module mnn) not found
  file utils.py (for module utils) not found
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/irlb.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/utils.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/mnn.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  copying mnnpy/settings.py -> build/lib.macosx-10.9-x86_64-3.7/mnnpy
  file irlb.py (for module irlb) not found
  file mnn.py (for module mnn) not found
  file utils.py (for module utils) not found
  running build_ext
  building 'mnnpy._utils' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/mnnpy
  /usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/kartik/opt/miniconda3/include -arch x86_64 -I/Users/kartik/opt/miniconda3/include -arch x86_64 -Imnnpy -I/Users/kartik/opt/miniconda3/include/python3.7m -c mnnpy/_utils.c -o build/temp.macosx-10.9-x86_64-3.7/mnnpy/_utils.o -O2 -ffast-math -march=native -fopenmp
  In file included from mnnpy/_utils.c:33:
  /Users/kartik/opt/miniconda3/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
     25 | #include <stdio.h>
        |          ^~~~~~~~~
  1 error generated.
  error: command '/usr/local/opt/llvm/bin/clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mnnpy`

**Comment by briney** [comment]
I haven't seen that problem before, but it looks like a problem building mnnpy and I'm probably not the best person to help debug mnnpy install issues. The mnnpy docs have this potential fix:

```
brew install gcc@8
export CC=/usr/local/Cellar/gcc@8/8.4.0/bin/gcc-8
pip install mnnpy
unset CC
```

and then install scab with `pip install scab` once mnnpy is already installed.

**Comment by kartikchandran** [comment]
Thank you! I did find this fix on the mnnpy docs and it worked! And I was able to install scab after that without any errors. However, I have another issue when trying to import scab in the jupyter notebook (Python noob, here—sorry!). I'll start another issue thread for that. 
Kartik
